// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewqxfmkqzloirhjnrjio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3cXhmbWtxemxvaXJoam5yamlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzNzIyNjMsImV4cCI6MjA1NTk0ODI2M30.Esbh5I72KaSapHoDak8Kvcs0jLK-BTaZXIwIafeeEKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);